name: Deploy na Produkciju

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Ovdje definišemo environment koji aktivira pravila zaštite
    environment: production
    steps:
      - name: Deploy u produkciju
        env:
          KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "Provjera pristupa..."
          # Job će ovdje pauzirati dok ne dobije odobrenje (ako je postavljeno)
          echo "Deployujem u produkciju..."
